add iniFile check
Senzing/g2loader pull request #81
Opened 2022-07-22 20:19 UTC by SamMacy

# Pull request questions

## Which issue does this address

Issue number: #77

2022-07-22 21:27 UTC, docktermj approved these changes

2022-07-25 23:41 UTC, jbutcher21 requested changes
left some debug code?  print('case 2')

2022-08-01 19:26 UTC, antaenc requested changes
@SamMacy 

1) Please review and modify to simplify the code

```
    #Check if INI file or env var is specified, otherwise use default INI file
    iniFileName = None

    if args.iniFile:
        iniFileName = pathlib.Path(args.iniFile[0])
    elif os.getenv("SENZING_ENGINE_CONFIGURATION_JSON"):
        g2module_params =  os.getenv("SENZING_ENGINE_CONFIGURATION_JSON")
    else:
        iniFileName = pathlib.Path(G2Paths.get_G2Module_ini_path())

    if iniFileName:
        G2Paths.check_file_exists_and_readable(iniFileName)
        iniParamCreator = G2IniParams()
        g2module_params = iniParamCreator.getJsonINIParams(iniFileName)
```

2) There is code after this still that would overwrite g2_module_params

```
    # If ini file isn't specified try and locate it with G2Paths
    iniFileName = pathlib.Path(G2Paths.get_G2Module_ini_path()) if not args.iniFile else pathlib.Path(args.iniFile[0]).resolve()
    G2Paths.check_file_exists_and_readable(iniFileName)

    # Get the INI parameters to use
    iniParamCreator = G2IniParams()
    g2module_params =  os.getenv("SENZING_ENGINE_CONFIGURATION_JSON", iniParamCreator.getJsonINIParams(iniFileName))
```

2022-08-01 19:52 UTC, antaenc approved these changes

2022-08-02 18:49 UTC, merged